name: Publish amis-admin front docker image
permissions: {}
on:
  push:
    branches: [ "dev" ]
    paths-ignore:
      - backend
      - .github/workflows/build-fb-data.yml
      - .github/workflows/build-fb-hook.yml
      - README.md

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # context: .
          platforms: linux/amd64,linux/arm64
          # file: Dockerfile
          push: true
          tags: fireboomapi/amis-admin_front:latest
